"""Print jobs against the fake printer: streaming, pause, cancel, estimates."""

import time
from pathlib import Path

import pytest

from printpi_daemon.job import JobError, JobState, SerialJobRunner, activity_of, pace_factor, scan_file
from printpi_daemon.printer import Printer

FAST = "fake://?time_scale=0.01"

SAMPLE = """; generated by PrusaSlicer 2.8
M73 P0 R120
M104 S200
G28
;LAYER_CHANGE
;Z:0.2
G1 X10 Y10 F3000
G1 X20 Y10 E1
;LAYER_CHANGE
G1 X20 Y20 E2

G1 X10 Y20 E3 ; trailing comment
M73 P100 R0
"""


def wait_for(predicate, timeout: float = 5.0) -> bool:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if predicate():
            return True
        time.sleep(0.01)
    return predicate()


@pytest.fixture
def printer():
    p = Printer(FAST, connect_timeout=1.0, ok_timeout=5.0, temperature_interval=1.0)
    p.connect()
    yield p
    if p._port is not None:
        p.disconnect()


@pytest.fixture
def seen() -> list[JobState]:
    return []


def runner_for(printer: Printer, seen: list[JobState]) -> SerialJobRunner:
    """A runner on the printer that also hears the printer's host actions, as the bridge wires it."""
    r = SerialJobRunner(lambda: printer, on_state=seen.append, publish_interval=0.0)
    printer.on_action = r.handle_action
    return r


@pytest.fixture
def runner(printer, seen):
    r = runner_for(printer, seen)
    yield r
    r.stop()


def gcode_file(tmp_path: Path, text: str, name: str = "part.gcode") -> str:
    path = tmp_path / name
    path.write_text(text)
    return str(path)


def commands(printer: Printer) -> list[str]:
    return printer._port.commands


def moves(count: int) -> str:
    return "".join(f"G1 X{i % 20} Y{i % 7} E{i * 0.1:.1f} F6000\n" for i in range(count))


def test_scan_file_counts_lines_layer_markers_and_command_bytes(tmp_path):
    command_bytes = sum(len(line) + 1 for line in SAMPLE.splitlines() if line.strip() and not line.startswith(";"))
    assert scan_file(gcode_file(tmp_path, SAMPLE)) == (13, 2, command_bytes)
    assert scan_file(gcode_file(tmp_path, "G28\nG1 X1", "no-newline.gcode")) == (2, 0, 9)
    assert scan_file(gcode_file(tmp_path, ";LAYER:0\nG1 X1\n;LAYER:1\nG1 X2\n", "cura.gcode")) == (4, 2, 12)
    assert scan_file(gcode_file(tmp_path, "G28\n; trailing comment", "comment-tail.gcode")) == (2, 0, 4)
    assert scan_file(gcode_file(tmp_path, "", "empty.gcode")) == (0, 0, 0)


def test_scan_file_handles_lines_across_chunks(tmp_path, monkeypatch):
    monkeypatch.setattr("printpi_daemon.job._SCAN_CHUNK", 7)
    text = "; header comment\n;LAYER_CHANGE\nG1 X10 Y10 E1 ; note\n\n;LAYER_CHANGE\nG1 X20\n"
    assert scan_file(gcode_file(tmp_path, text)) == (6, 2, len("G1 X10 Y10 E1 ; note\n") + len("G1 X20\n"))


def test_progress_ignores_the_comment_blocks_a_slicer_embeds(printer, runner, tmp_path):
    # A thumbnail header the size of the whole print must not move the bar before the first command.
    thumbnail = "; thumbnail begin 480x240 4000\n" + "; " * 20 + ("; " + "A" * 76 + "\n") * 60 + "; thumbnail end\n"
    text = thumbnail + "G28\nG4 S100\n" + moves(20)
    runner.start(gcode_file(tmp_path, text))
    # The dwell holds the stream on line 64, right after the header was skipped.
    assert wait_for(lambda: runner.state.line >= 63)
    job = runner.state
    assert job.total_bytes == len(text) - len(thumbnail)
    assert job.progress < 0.05
    assert wait_for(lambda: runner.state.state == "finished")
    assert runner.state.bytes_sent == runner.state.total_bytes


def test_m73_percent_sets_the_progress(printer, runner, tmp_path):
    runner.start(gcode_file(tmp_path, "M73 P0 R120\nG28\nM73 P42 R70\nG4 S100\n" + moves(30)))
    assert wait_for(lambda: runner.state.line >= 4)
    assert runner.state.progress == pytest.approx(0.42)
    assert wait_for(lambda: runner.state.state == "finished")
    assert runner.state.progress == 1.0


def test_streams_the_file_and_finishes(printer, runner, seen, tmp_path):
    path = gcode_file(tmp_path, SAMPLE)
    job = runner.start(path, name="Benchy.gcode", file_id=7, estimated_seconds=600)
    assert job.state == "printing" and job.name == "Benchy.gcode" and job.file_id == 7
    assert printer.state.status == "printing"

    assert wait_for(lambda: runner.state.state == "finished")
    sent = commands(printer)
    assert sent[-1] == "M400"  # the end waits for the last moves before the job is over
    sent = sent[:-1]
    assert sent[-6:] == ["G1 X10 Y10 F3000", "G1 X20 Y10 E1", "G1 X20 Y20 E2", "G1 X10 Y20 E3", "M73 P100 R0", "M105"] or \
        sent[-5:] == ["G1 X10 Y10 F3000", "G1 X20 Y10 E1", "G1 X20 Y20 E2", "G1 X10 Y20 E3", "M73 P100 R0"]
    assert not any(command.startswith(";") for command in sent)

    final = runner.state
    assert final.progress == 1.0
    assert final.line == final.total_lines == 13
    assert final.layer == final.total_layers == 2
    assert final.bytes_sent == final.total_bytes == scan_file(path)[2]
    assert final.finished_at is not None and final.elapsed > 0
    assert final.remaining == 0.0 and final.error is None
    assert printer.state.status == "idle"
    assert [state.state for state in seen][0] == "printing"
    assert seen[-1].state == "finished"
    assert any(state.layer == 1 for state in seen) and any(state.layer == 2 for state in seen)


def test_m73_gives_the_remaining_time(printer, runner, tmp_path):
    runner.start(gcode_file(tmp_path, "M73 P0 R120\nG4 S100\nG1 X1\n"))
    assert wait_for(lambda: runner.state.line >= 1)
    job = runner.state
    assert job.remaining_source == "m73"
    assert job.remaining == pytest.approx(7200, abs=5)
    assert wait_for(lambda: runner.state.state == "finished")


def test_pause_holds_the_stream_and_is_not_counted_as_print_time(printer, runner, tmp_path):
    runner.start(gcode_file(tmp_path, "G4 S30\n" + moves(150)))
    runner.pause()
    assert wait_for(lambda: runner.state.state == "paused")
    assert printer.state.status == "paused"
    with pytest.raises(JobError, match="no print is running"):
        runner.pause()

    sent_before = len(commands(printer))
    time.sleep(0.3)
    assert len(commands(printer)) == sent_before
    paused_job = runner.state
    time.sleep(0.1)
    assert runner.state.elapsed == pytest.approx(paused_job.elapsed, abs=0.02)

    started = time.monotonic()
    runner.resume()
    assert wait_for(lambda: runner.state.state == "finished")
    assert runner.state.elapsed < (time.monotonic() - started) + 0.35
    # Every line went out exactly once, the pause only delayed them (its park script aside).
    file_lines = [c for c in commands(printer)[4:] if c == "G4 S30" or (c.startswith("G1 X") and " E" in c)]
    assert file_lines == ["G4 S30", *moves(150).splitlines()]
    with pytest.raises(JobError, match="not paused"):
        runner.resume()


def test_cancel_stops_the_stream_and_runs_the_cancel_script(printer, runner, tmp_path):
    runner.start(gcode_file(tmp_path, "G4 S30\n" + moves(100)))
    runner.cancel()
    assert runner.state.state == "cancelling"
    runner.cancel()  # a second cancel is harmless

    assert wait_for(lambda: runner.state.state == "cancelled")
    sent = commands(printer)
    assert sent[-len(runner.cancel_gcode):] == runner.cancel_gcode
    assert "G1 X1 Y1 E0.1 F6000" not in sent
    assert runner.state.progress < 1.0
    assert printer.state.status == "idle"
    with pytest.raises(JobError, match="no print is running"):
        runner.cancel()


def test_cancel_while_paused(printer, runner, tmp_path):
    runner.start(gcode_file(tmp_path, "G4 S30\n" + moves(50)))
    runner.pause()
    assert wait_for(lambda: runner.state.state == "paused")
    runner.cancel()
    assert wait_for(lambda: runner.state.state == "cancelled")
    assert commands(printer)[-1] == "M84"


def test_cancel_interrupts_a_heat_up(printer, runner, tmp_path):
    # M190 S100 would take over a second even at the fake's speed; M108 cuts it short.
    runner.start(gcode_file(tmp_path, "M190 S100\n" + moves(10)))
    assert wait_for(lambda: "M190 S100" in commands(printer))
    started = time.monotonic()
    runner.cancel()
    assert wait_for(lambda: runner.state.state == "cancelled")
    assert time.monotonic() - started < 0.6


def test_disconnect_fails_the_job(printer, runner, tmp_path):
    runner.start(gcode_file(tmp_path, "G4 S100\nG4 S100\n" + moves(10)))
    assert wait_for(lambda: "G4 S100" in commands(printer))
    printer.disconnect()
    assert wait_for(lambda: runner.state.state == "error")
    assert "disconnected" in runner.state.error
    assert runner.state.finished_at is not None


def test_start_refuses_while_running_or_disconnected(printer, runner, tmp_path):
    path = gcode_file(tmp_path, "G4 S50\n")
    runner.start(path)
    with pytest.raises(JobError, match="already running"):
        runner.start(path)
    assert wait_for(lambda: runner.state.state == "finished")

    with pytest.raises(JobError, match="does not exist"):
        runner.start(str(tmp_path / "missing.gcode"))
    printer.disconnect()
    with pytest.raises(JobError, match="not connected"):
        runner.start(path)


def test_restart_prints_the_last_job_again(printer, runner, tmp_path):
    with pytest.raises(JobError, match="nothing to print"):
        runner.restart()
    path = gcode_file(tmp_path, SAMPLE)
    runner.start(path, name="again.gcode", file_id=3, estimated_seconds=42)
    assert wait_for(lambda: runner.state.state == "finished")
    first_started = runner.state.started_at

    job = runner.restart()
    assert job.state == "printing" and job.name == "again.gcode" and job.file_id == 3 and job.estimated_seconds == 42
    assert job.progress == 0.0 and job.line == 0 and job.started_at >= first_started
    assert wait_for(lambda: runner.state.state == "finished")
    assert commands(printer).count("G1 X20 Y20 E2") == 2


def test_temperatures_are_polled_without_autoreport(printer, runner, tmp_path):
    printer.state.capabilities["AUTOREPORT_TEMP"] = False
    printer.temperature_interval = 0.05
    runner.start(gcode_file(tmp_path, "G4 S10\n" * 8))
    assert wait_for(lambda: runner.state.state == "finished")
    sent = commands(printer)
    assert "M105" in sent[sent.index("G4 S10"):]


def test_remaining_time_estimates(printer, runner):
    job = JobState(name="x", path="x", estimated_seconds=1000)
    job.progress = 0.01
    # Before the first layer the slicer's figure stands still: heating is not part of it.
    assert runner._estimate_remaining(job, 100.0) == (1000.0, "slicer")
    runner._print_started_at = 0.0
    assert runner._estimate_remaining(job, 100.0) == (900.0, "slicer")
    job.progress = 0.5
    assert runner._estimate_remaining(job, 100.0) == (pytest.approx(500.0), "slicer")
    job.estimated_seconds = None
    assert runner._estimate_remaining(job, 100.0) == (pytest.approx(100.0), "progress")
    job.progress = 0.01
    assert runner._estimate_remaining(job, 100.0) == (None, None)
    job.estimated_seconds = 50
    assert runner._estimate_remaining(job, 100.0) == (0.0, "slicer")


def test_m73_remaining_holds_before_the_first_layer_and_follows_the_pace_after(printer, runner):
    job = JobState(name="x", path="x")
    runner._m73 = (7200.0, 10.0, None)  # seen with 10 s elapsed, slicer at P0
    assert runner._estimate_remaining(job, 200.0) == (7200.0, "m73")

    runner._print_started_at = 180.0
    runner._m73 = (3600.0, 180.0, None)
    assert runner._estimate_remaining(job, 240.0) == (pytest.approx(3540.0), "m73")

    # Halfway by the slicer's clock (P50 R30 → it expected 1800 s) after 3600 s of real printing: twice as slow.
    runner._m73 = (1800.0, 180.0 + 3600.0, 1800.0)
    assert runner._estimate_remaining(job, 180.0 + 3600.0 + 60.0) == (pytest.approx(3540.0), "m73")
    assert pace_factor(3600.0, 1800.0) == 2.0
    assert pace_factor(60.0, 30.0) == 1.0  # too early to judge
    assert pace_factor(9000.0, 1800.0) == 2.5  # clamped

    # The slicer's estimate ran out while the print goes on: the pace by progress takes over.
    runner._m73 = (60.0, 1000.0, None)
    job.progress = 0.98
    remaining, source = runner._estimate_remaining(job, 2000.0)
    assert source == "progress" and remaining == pytest.approx(2000.0 / 0.98 - 2000.0)


def test_activity_of_start_gcode_commands():
    assert activity_of("M109 T0 R170 ; wait for temp") == "heating"
    assert activity_of("M190 S60") == "heating"
    assert activity_of("M104 S230") is None
    assert activity_of("G28 ; home all") == "homing"
    assert activity_of("G29 P9 X10 Y-4 W32 H4") == "cleaning"
    assert activity_of("G29 P1 X0 Y0 W50 H20 C") == "leveling"
    assert activity_of("G80") == "leveling"
    assert activity_of("M701") == "loading"
    assert activity_of("G0 E7 X15 Z0.2 F500 ; purge") == "purging"
    assert activity_of("G1 E2 F2400 ; deretraction") is None
    assert activity_of("G1 X42 Y-4 Z5 F4800") is None
    assert activity_of("M862.3 P \"MK4S\"") is None


def test_activity_follows_the_start_gcode_and_ends_with_the_first_layer(printer, runner, seen, tmp_path):
    text = "M73 P0 R120\nM109 S200\nG28\nG29\nG0 X10 E5\n;LAYER_CHANGE\nG1 X1 E1\nM109 S210\n" + moves(5)
    runner.start(gcode_file(tmp_path, text))
    assert wait_for(lambda: runner.state.state == "finished")
    activities = []
    for state in seen:
        if not activities or activities[-1] != state.activity:
            activities.append(state.activity)
    assert activities == ["preparing", "heating", "homing", "leveling", "purging", None]
    assert runner.state.activity is None


def test_every_run_gets_its_own_id_and_energy_counts_only_while_active(printer, runner, tmp_path):
    path = gcode_file(tmp_path, "G4 S30\n" + moves(20))
    job = runner.start(path)
    assert len(job.id) == 12 and job.energy_wh is None
    runner.add_energy(1.5)
    runner.add_energy(0.5)
    runner.add_energy(-3.0)  # never subtracts
    assert runner.state.energy_wh == pytest.approx(2.0)
    runner.cancel()
    assert wait_for(lambda: runner.state.state == "cancelled")
    runner.add_energy(1.0)
    assert runner.state.energy_wh == pytest.approx(2.0)

    again = runner.restart()
    assert again.id != job.id and again.energy_wh is None
    assert wait_for(lambda: runner.state.state == "finished")


def test_a_print_survives_lines_lost_on_the_wire(seen, tmp_path):
    # Every 9th line vanishes before the printer sees it. Without the probe the job
    # would end with "no ok within timeout"; with it every move still arrives in order.
    printer = Printer(FAST + "&drop_every=9", connect_timeout=1.0, ok_timeout=2.0, probe_timeout=0.05)
    printer.connect()
    runner = SerialJobRunner(lambda: printer, on_state=seen.append, publish_interval=0.0)
    try:
        runner.start(gcode_file(tmp_path, moves(40)), name="part.gcode", file_id=1, estimated_seconds=60)
        assert wait_for(lambda: runner.state.state in ("finished", "error"), timeout=15.0)
        assert runner.state.state == "finished", runner.state.error
        sent = [command for command in commands(printer) if command.startswith("G1 ")]
        assert sent == moves(40).splitlines()
        assert printer._port.last_line == printer._line_number - 1
    finally:
        runner.stop()
        printer.disconnect()


BED = {"x": 250, "y": 210, "z": 220, "centered": False}


def prusa_printer(firmware: str) -> Printer:
    p = Printer(FAST + f"&firmware={firmware}", connect_timeout=1.0, ok_timeout=5.0, temperature_interval=1.0)
    p.connect()
    return p


def paused_job(runner, printer, tmp_path, seen, count: int = 60):
    """Start a print and pause it a few moves in; returns once the runner reports paused."""
    runner.start(gcode_file(tmp_path, moves(count)), name="part.gcode", file_id=1, estimated_seconds=60, bed=BED)
    assert wait_for(lambda: runner.state.line >= 5)
    runner.pause()
    assert wait_for(lambda: runner.state.state == "paused")


def test_pause_on_plain_marlin_parks_the_head_and_the_resume_puts_it_back(printer, runner, seen, tmp_path):
    paused_job(runner, printer, tmp_path, seen)
    sent = commands(printer)
    park = sent.index("M400")
    assert sent[park:park + 8] == ["M400", "M114", "M83", "G1 E-2 F2400", "G91", "G1 Z5 F600", "G90", "G1 X5.0 Y205.0 F6000"]
    assert any(state.activity == "pausing" for state in seen)
    assert printer.state.status == "paused"

    runner.resume()
    assert wait_for(lambda: runner.state.state == "finished", timeout=15.0)
    sent = commands(printer)
    back = sent.index("G90", park + 8)
    fake = printer._port
    x, y = fake.position["X"], fake.position["Y"]  # wherever the file ends, the head went back before continuing
    assert sent[back].startswith("G90") and sent[back + 1].startswith("G1 X") and sent[back + 2].startswith("G1 Z")
    assert sent[back + 3:back + 5] == ["M83", "G1 E2 F2400"]
    assert sent[back + 5].startswith("G92 E")
    assert sent[back + 6:back + 9] == ["M82", "G90", "G1 F6000"]
    moves_sent = [command for command in sent if command.startswith("G1 X") and " E" in command]
    assert moves_sent == moves(60).splitlines()
    assert any(state.activity == "resuming" for state in seen)
    assert runner.state.activity is None
    assert runner.state.error is None and (x, y) != (5.0, 205.0)


def test_pause_on_buddy_uses_m601_and_the_resume_waits_for_the_printer(seen, tmp_path):
    printer = prusa_printer("buddy")
    runner = runner_for(printer, seen)
    fake = printer._port
    fake.resume_delay = None  # the host action comes when the test says so
    try:
        paused_job(runner, printer, tmp_path, seen)
        sent = commands(printer)
        assert sent[-1] == "M601" and "M400" not in sent
        assert fake.paused

        runner.resume()
        assert wait_for(lambda: runner.state.activity == "resuming")
        assert wait_for(lambda: commands(printer)[-1] == "M602")
        time.sleep(0.2)
        assert commands(printer)[-1] == "M602"  # nothing streams until the printer reports the resume
        assert runner.state.state == "printing"

        fake.host_action("resume")
        assert wait_for(lambda: runner.state.state == "finished", timeout=15.0)
        sent = commands(printer)
        assert sent.count("M601") == 1 and sent.count("M602") == 1
        assert [command for command in sent if command.startswith("G1 X")] == moves(60).splitlines()
    finally:
        runner.stop()
        printer.disconnect()


def test_a_pause_and_resume_at_the_buddy_screen_drive_the_job(seen, tmp_path):
    printer = prusa_printer("buddy")
    runner = runner_for(printer, seen)
    fake = printer._port
    try:
        runner.start(gcode_file(tmp_path, moves(60)), name="part.gcode", file_id=1, estimated_seconds=60, bed=BED)
        assert wait_for(lambda: runner.state.line >= 5)
        fake.host_action("pause")  # Buddy has parked already and tells the host
        assert wait_for(lambda: runner.state.state == "paused")
        assert commands(printer)[-1] == "M601"  # harmless on a printer that is paused already

        fake.paused = False
        fake.host_action("resume")  # reheated and back in position, the screen's resume
        assert wait_for(lambda: runner.state.state == "finished", timeout=15.0)
        assert "M602" not in commands(printer)
        assert [command for command in commands(printer) if command.startswith("G1 X")] == moves(60).splitlines()
    finally:
        runner.stop()
        printer.disconnect()


def test_pause_on_the_mk3_waits_for_m602_to_return(seen, tmp_path):
    printer = prusa_printer("prusa")
    runner = runner_for(printer, seen)
    fake = printer._port
    try:
        paused_job(runner, printer, tmp_path, seen)
        assert commands(printer)[-1] == "M601"
        assert wait_for(lambda: runner._printer_paused)  # "//action:paused" arrived

        runner.resume()
        assert wait_for(lambda: runner.state.state == "finished", timeout=15.0)
        sent = commands(printer)
        assert sent.count("M602") == 1
        assert [command for command in sent if command.startswith("G1 X")] == moves(60).splitlines()
    finally:
        runner.stop()
        printer.disconnect()


def test_the_mk3_screen_asks_the_host_to_pause_and_resume(seen, tmp_path):
    printer = prusa_printer("prusa")
    runner = runner_for(printer, seen)
    fake = printer._port
    try:
        runner.start(gcode_file(tmp_path, moves(60)), name="part.gcode", file_id=1, estimated_seconds=60, bed=BED)
        assert wait_for(lambda: runner.state.line >= 5)
        fake.host_action("pause")  # the MK3 only asks; the host has to send M601
        assert wait_for(lambda: runner.state.state == "paused")
        assert wait_for(lambda: fake.paused)

        fake.host_action("resume")  # and asks again on resume
        assert wait_for(lambda: runner.state.state == "finished", timeout=15.0)
        sent = commands(printer)
        assert sent.count("M601") == 1 and sent.count("M602") == 1
    finally:
        runner.stop()
        printer.disconnect()


def test_a_cancel_at_the_printer_ends_the_job(seen, tmp_path):
    printer = prusa_printer("buddy")
    runner = runner_for(printer, seen)
    try:
        runner.start(gcode_file(tmp_path, moves(200)), name="part.gcode", file_id=1, estimated_seconds=60, bed=BED)
        assert wait_for(lambda: runner.state.line >= 5)
        printer._port.host_action("cancel")
        assert wait_for(lambda: runner.state.state == "cancelled", timeout=10.0)
        assert commands(printer)[-len(runner.cancel_gcode):] == runner.cancel_gcode
    finally:
        runner.stop()
        printer.disconnect()


END_GCODE = "G1 Z10 F720 ; lift\nG1 X241 Y170 F3600 ; park\nM104 S0\nM84\n"


def test_the_closing_frame_is_taken_after_the_end_gcode(printer, seen, tmp_path):
    complete: list[tuple[str, int, list[str]]] = []
    runner = SerialJobRunner(
        lambda: printer,
        on_state=seen.append,
        on_complete=lambda job: complete.append((job.state, job.line, commands(printer)[-3:])),
        publish_interval=0.0,
    )
    try:
        text = moves(20) + "G1 X3 Y3 E-0.8 ; wipe\n" + END_GCODE
        runner.start(gcode_file(tmp_path, text), name="part.gcode")
        assert wait_for(lambda: runner.state.state == "finished")
        # The whole file was out and its moves flushed with M400 when the listener ran, and the
        # job still counted as printing so the frame lands before the record goes out.
        assert complete == [("printing", text.count("\n"), ["M104 S0", "M84", "M400"])]
        assert commands(printer)[-1] == "M400"
    finally:
        runner.stop()


def test_a_cancel_script_of_the_jobs_own_is_kept_for_the_restart(printer, runner, tmp_path):
    path = gcode_file(tmp_path, "G4 S30\n" + moves(100))
    runner.start(path, cancel_gcode=["M104 S0", "", "G28 X"])
    runner.cancel()
    assert wait_for(lambda: runner.state.state == "cancelled")
    assert commands(printer)[-2:] == ["M104 S0", "G28 X"]

    runner.restart()
    runner.cancel()
    assert wait_for(lambda: runner.state.state == "cancelled")
    assert commands(printer)[-2:] == ["M104 S0", "G28 X"]

    # A start without a script goes back to the built-in one.
    runner.start(path)
    runner.cancel()
    assert wait_for(lambda: runner.state.state == "cancelled")
    assert commands(printer)[-len(runner.cancel_gcode):] == runner.cancel_gcode
