<?php

namespace Tests\Feature;

use App\Models\GcodeFile;
use App\Models\User;
use App\Services\PrinterBridge;
use App\Services\Settings;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Mockery\MockInterface;
use Tests\TestCase;

class GcodeFileApiTest extends TestCase
{
    use RefreshDatabase;

    private const string SAMPLE = <<<'GCODE'
    ; generated by PrusaSlicer 2.8.1+MacOS on 2026-09-01 at 10:00:00 UTC
    M104 S215
    M140 S60
    G28
    G1 X10 Y10 F3000
    ; estimated printing time (normal mode) = 1h 23m 45s
    ; filament used [mm] = 1234.56
    ; filament used [g] = 3.68
    ; layer_height = 0.2
    ; temperature = 215
    ; bed_temperature = 60
    GCODE;

    private const string PNG = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==';

    private const string WITH_THUMBNAIL = "; generated by PrusaSlicer 2.8.1+MacOS\n;\n; thumbnail begin 16x16 96\n; ".self::PNG."\n; thumbnail end\n;\nG28\n";

    protected function setUp(): void
    {
        parent::setUp();
        $this->actingAs(User::factory()->create());
        Storage::fake('gcode');
        // Every upload asks the daemon's state whether the file is being printed; no job by default.
        $this->mock(PrinterBridge::class, function (MockInterface $mock): void {
            $mock->shouldReceive('activeJob')->andReturnNull()->byDefault();
        });
    }

    public function test_upload_stores_file_and_parses_metadata(): void
    {
        $upload = UploadedFile::fake()->createWithContent('Benchy (0.2mm).gcode', self::SAMPLE);

        $this->postJson(route('files.store'), ['file' => $upload])
            ->assertCreated()
            ->assertJsonPath('data.name', 'Benchy (0.2mm).gcode')
            ->assertJsonPath('data.size', strlen(self::SAMPLE))
            ->assertJsonPath('data.metadata.slicer', 'PrusaSlicer 2.8.1+MacOS')
            ->assertJsonPath('data.metadata.estimated_seconds', 5025)
            ->assertJsonPath('data.metadata.nozzle_temperature', 215)
            ->assertJsonPath('data.metadata.bed_temperature', 60)
            ->assertJsonPath('data.thumbnail_url', null);

        Storage::disk('gcode')->assertExists('Benchy (0.2mm).gcode');
        $this->assertDatabaseHas('gcode_files', ['name' => 'Benchy (0.2mm).gcode']);
    }

    public function test_upload_extracts_the_embedded_thumbnail(): void
    {
        $response = $this->postJson(route('files.store'), [
            'file' => UploadedFile::fake()->createWithContent('benchy.gcode', self::WITH_THUMBNAIL),
        ])->assertCreated();

        $id = $response->json('data.id');
        $this->assertStringStartsWith("/api/v1/files/{$id}/thumbnail?v=", $response->json('data.thumbnail_url'));
        $this->assertSame("/api/v1/files/{$id}/download", $response->json('data.download_url'));
        Storage::disk('gcode')->assertExists("thumbnails/{$id}.png");
        $this->assertSame(base64_decode(self::PNG, true), Storage::disk('gcode')->get("thumbnails/{$id}.png"));

        $this->get(route('files.thumbnail', $id))
            ->assertOk()
            ->assertHeader('Content-Type', 'image/png');
    }

    public function test_replacing_a_file_without_thumbnail_drops_the_old_image(): void
    {
        $this->postJson(route('files.store'), ['file' => UploadedFile::fake()->createWithContent('part.gcode', self::WITH_THUMBNAIL)])->assertCreated();
        $id = GcodeFile::query()->sole()->id;
        Storage::disk('gcode')->assertExists("thumbnails/{$id}.png");

        $this->postJson(route('files.store'), ['file' => UploadedFile::fake()->createWithContent('part.gcode', 'G28')])
            ->assertCreated()
            ->assertJsonPath('data.thumbnail_url', null);

        Storage::disk('gcode')->assertMissing("thumbnails/{$id}.png");
        $this->get(route('files.thumbnail', $id))->assertNotFound();
    }

    public function test_upload_with_same_name_replaces_the_file(): void
    {
        $this->postJson(route('files.store'), ['file' => UploadedFile::fake()->createWithContent('part.gcode', 'G28')])->assertCreated();
        $this->postJson(route('files.store'), ['file' => UploadedFile::fake()->createWithContent('part.gcode', self::SAMPLE)])->assertCreated();

        $this->assertDatabaseCount('gcode_files', 1);
        $this->assertSame(self::SAMPLE, Storage::disk('gcode')->get('part.gcode'));
    }

    public function test_upload_refuses_to_replace_the_file_being_printed(): void
    {
        Storage::disk('gcode')->put('part.gcode', 'G28');
        GcodeFile::factory()->create(['name' => 'part.gcode']);
        $this->mock(PrinterBridge::class, function (MockInterface $mock): void {
            $mock->shouldReceive('activeJob')->andReturn(['state' => 'printing', 'path' => Storage::disk('gcode')->path('part.gcode')]);
        });

        $this->postJson(route('files.store'), ['file' => UploadedFile::fake()->createWithContent('part.gcode', self::SAMPLE)])
            ->assertStatus(409)
            ->assertJsonPath('message', 'This file is being printed right now.');
        $this->assertSame('G28', Storage::disk('gcode')->get('part.gcode'));

        $this->postJson(route('files.store'), ['file' => UploadedFile::fake()->createWithContent('other.gcode', 'G28')])->assertCreated();
    }

    public function test_upload_strips_directories_from_the_name(): void
    {
        $this->postJson(route('files.store'), ['file' => UploadedFile::fake()->createWithContent('../../etc/evil.gcode', 'G28')])
            ->assertCreated()
            ->assertJsonPath('data.name', 'evil.gcode');
    }

    public function test_upload_rejects_other_file_types(): void
    {
        $this->postJson(route('files.store'), ['file' => UploadedFile::fake()->create('notes.txt', 1)])
            ->assertUnprocessable()
            ->assertJsonValidationErrors('file');
        $this->assertDatabaseCount('gcode_files', 0);
    }

    public function test_index_lists_files_newest_first(): void
    {
        $older = GcodeFile::factory()->create(['updated_at' => now()->subHour()]);
        $newer = GcodeFile::factory()->create(['updated_at' => now()]);

        $this->getJson(route('files.index'))
            ->assertOk()
            ->assertJsonCount(2, 'data')
            ->assertJsonPath('data.0.id', $newer->id)
            ->assertJsonPath('data.1.id', $older->id)
            ->assertJsonStructure(['data' => [['id', 'name', 'size', 'metadata', 'thumbnail_url', 'download_url', 'uploaded_at']]]);
    }

    public function test_download_streams_the_file(): void
    {
        $file = GcodeFile::factory()->create(['name' => 'part.gcode']);
        Storage::disk('gcode')->put('part.gcode', self::SAMPLE);

        $response = $this->get(route('files.download', $file))
            ->assertOk()
            ->assertDownload('part.gcode');

        $this->assertSame(self::SAMPLE, $response->streamedContent());
    }

    public function test_destroy_removes_file_thumbnail_and_record(): void
    {
        $file = GcodeFile::factory()->create(['name' => 'gone.gcode', 'thumbnail' => 'thumbnails/7.png']);
        Storage::disk('gcode')->put('gone.gcode', 'G28');
        Storage::disk('gcode')->put('thumbnails/7.png', base64_decode(self::PNG, true));

        $this->deleteJson(route('files.destroy', $file))->assertNoContent();

        Storage::disk('gcode')->assertMissing('gone.gcode');
        Storage::disk('gcode')->assertMissing('thumbnails/7.png');
        $this->assertDatabaseMissing('gcode_files', ['id' => $file->id]);
    }

    public function test_file_routes_require_login(): void
    {
        auth()->logout();
        $file = GcodeFile::factory()->create();

        $this->getJson(route('files.download', $file))->assertUnauthorized();
        $this->getJson(route('files.thumbnail', $file))->assertUnauthorized();
    }

    public function test_print_hands_the_daemon_the_path_and_the_estimate(): void
    {
        $file = GcodeFile::factory()->create(['name' => 'Benchy.gcode', 'metadata' => ['estimated_seconds' => 5025]]);
        $path = Storage::disk('gcode')->path('Benchy.gcode');

        $this->mock(PrinterBridge::class, function (MockInterface $mock) use ($file, $path): void {
            $mock->shouldReceive('isConnected')->once()->andReturn(true);
            $mock->shouldReceive('hasActiveJob')->once()->andReturn(false);
            $mock->shouldReceive('startPrint')->once()->with($path, 'Benchy.gcode', $file->id, 5025, null, null, ['enabled' => true, 'gif' => true, 'mp4' => true], null);
        });

        $this->postJson(route('files.print', $file))
            ->assertStatus(202)
            ->assertJsonPath('queued', true);
    }

    public function test_print_passes_the_bed_of_the_configured_printer(): void
    {
        $file = GcodeFile::factory()->create(['name' => 'raw.gcode', 'metadata' => []]);
        app(Settings::class)->set(['printer_profile' => 'prusa-mk4s']);

        $this->mock(PrinterBridge::class, function (MockInterface $mock): void {
            $mock->shouldReceive('isConnected')->andReturn(true);
            $mock->shouldReceive('hasActiveJob')->andReturn(false);
            $mock->shouldReceive('startPrint')->once()->withArgs(
                fn (string $path, string $name, int $id, ?int $estimate, ?string $camera, ?array $bed): bool => $bed === ['x' => 250, 'y' => 210, 'z' => 220, 'centered' => false],
            );
        });

        $this->postJson(route('files.print', $file))->assertStatus(202);
    }

    public function test_print_without_an_estimate_passes_null(): void
    {
        $file = GcodeFile::factory()->create(['name' => 'raw.gcode', 'metadata' => []]);

        $this->mock(PrinterBridge::class, function (MockInterface $mock) use ($file): void {
            $mock->shouldReceive('isConnected')->andReturn(true);
            $mock->shouldReceive('hasActiveJob')->andReturn(false);
            $mock->shouldReceive('startPrint')->once()->withArgs(fn (string $path, string $name, int $id, ?int $estimate, ?string $camera): bool => $name === 'raw.gcode' && $id === $file->id && $estimate === null && $camera === null);
        });

        $this->postJson(route('files.print', $file))->assertStatus(202);
    }

    public function test_print_passes_the_stream_url_of_a_camera_the_daemon_does_not_run(): void
    {
        $file = GcodeFile::factory()->create(['name' => 'raw.gcode', 'metadata' => []]);
        app(Settings::class)->set(['camera_url' => 'http://192.168.1.50:8080/?action=stream']);

        $cameras = [];
        $this->mock(PrinterBridge::class, function (MockInterface $mock) use (&$cameras): void {
            $mock->shouldReceive('isConnected')->andReturn(true);
            $mock->shouldReceive('hasActiveJob')->andReturn(false);
            $mock->shouldReceive('startPrint')->twice()->andReturnUsing(function (string $path, string $name, int $id, ?int $estimate, ?string $camera) use (&$cameras): void {
                $cameras[] = $camera;
            });
        });
        $this->postJson(route('files.print', $file))->assertStatus(202);

        // A USB camera the daemon streams itself needs no URL, the daemon knows its own snapshot endpoint.
        app(Settings::class)->set(['camera_device' => '/dev/video0']);
        $this->postJson(route('files.print', $file))->assertStatus(202);

        $this->assertSame(['http://192.168.1.50:8080/?action=stream', null], $cameras);
    }

    public function test_print_is_refused_without_a_connection_or_while_printing(): void
    {
        $file = GcodeFile::factory()->create();

        $this->mock(PrinterBridge::class, function (MockInterface $mock): void {
            $mock->shouldReceive('isConnected')->twice()->andReturn(false, true);
            $mock->shouldReceive('hasActiveJob')->once()->andReturn(true);
            $mock->shouldNotReceive('startPrint');
        });

        $this->postJson(route('files.print', $file))
            ->assertStatus(409)
            ->assertJsonPath('message', 'The printer is not connected.');
        $this->postJson(route('files.print', $file))
            ->assertStatus(409)
            ->assertJsonPath('message', 'A print is already running.');
    }

    public function test_print_passes_the_timelapse_choice_and_the_cancel_script(): void
    {
        $file = GcodeFile::factory()->create(['name' => 'raw.gcode', 'metadata' => []]);
        app(Settings::class)->set(['timelapse' => true, 'timelapse_gif' => false, 'timelapse_mp4' => true, 'cancel_gcode' => "M104 S0\r\n\n  M140 S0  \n"]);

        $this->mock(PrinterBridge::class, function (MockInterface $mock): void {
            $mock->shouldReceive('isConnected')->andReturn(true);
            $mock->shouldReceive('hasActiveJob')->andReturn(false);
            $mock->shouldReceive('startPrint')->once()->withArgs(
                fn (string $path, string $name, int $id, ?int $estimate, ?string $camera, ?array $bed, ?array $timelapse, ?array $cancel): bool => $timelapse === ['enabled' => true, 'gif' => false, 'mp4' => true] && $cancel === ['M104 S0', 'M140 S0'],
            );
        });

        $this->postJson(route('files.print', $file))->assertStatus(202);
    }
}
