<?php

namespace Tests\Feature;

use App\Models\GcodeFile;
use App\Models\User;
use App\Services\PrinterBridge;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Mockery\MockInterface;
use Tests\TestCase;

/**
 * What PrusaSlicer, OrcaSlicer and Cura send to a print host: no session, no CSRF
 * token, no Accept header, only the X-Api-Key header on a plain multipart POST.
 */
class PrintHostApiTest extends TestCase
{
    use RefreshDatabase;

    private const string KEY = 'A1B2C3D4E5F6A1B2C3D4E5F6A1B2C3D4';

    private const string SAMPLE = "; generated by PrusaSlicer 2.8.1+MacOS on 2026-09-01 at 10:00:00 UTC\nG28\n; estimated printing time (normal mode) = 1h 23m 45s\n";

    protected function setUp(): void
    {
        parent::setUp();
        User::factory()->create(['api_key' => self::KEY]);
        Storage::fake('gcode');
        $this->mock(PrinterBridge::class, function (MockInterface $mock): void {
            $mock->shouldReceive('activeJob')->andReturnNull()->byDefault();
        });
    }

    public function test_version_answers_without_a_host_type(): void
    {
        $this->get(route('printhost.version'), ['X-Api-Key' => self::KEY])
            ->assertOk()
            ->assertJsonPath('api', '0.1')
            ->assertJsonPath('server', '1.5.0')
            ->assertJsonMissingPath('text');
    }

    public function test_requests_without_a_valid_key_are_refused(): void
    {
        $this->get(route('printhost.version'))->assertForbidden()->assertSee('Invalid API key');
        $this->get(route('printhost.version'), ['X-Api-Key' => 'wrong'])->assertForbidden();
        $this->post(route('printhost.upload'), ['file' => UploadedFile::fake()->createWithContent('part.gcode', 'G28')])->assertForbidden();
        $this->assertDatabaseCount('gcode_files', 0);

        // A user without a key must not match an empty header.
        User::factory()->create(['api_key' => null]);
        $this->get(route('printhost.version'), ['X-Api-Key' => ''])->assertForbidden();
    }

    public function test_upload_stores_the_file_in_the_library(): void
    {
        $upload = UploadedFile::fake()->createWithContent('Benchy (0.2mm).gcode', self::SAMPLE);

        $this->post(route('printhost.upload'), ['file' => $upload, 'print' => 'false', 'path' => ''], ['X-Api-Key' => self::KEY])
            ->assertCreated()
            ->assertJsonPath('done', true)
            ->assertJsonPath('files.local.name', 'Benchy (0.2mm).gcode')
            ->assertJsonPath('files.local.origin', 'local')
            ->assertJsonPath('files.local.path', 'Benchy (0.2mm).gcode');

        Storage::disk('gcode')->assertExists('Benchy (0.2mm).gcode');
        $this->assertDatabaseHas('gcode_files', ['name' => 'Benchy (0.2mm).gcode']);
        $this->assertSame(5025, GcodeFile::query()->sole()->metadata['estimated_seconds']);
    }

    public function test_upload_with_print_starts_the_job(): void
    {
        $this->mock(PrinterBridge::class, function (MockInterface $mock): void {
            $mock->shouldReceive('activeJob')->andReturnNull();
            $mock->shouldReceive('isConnected')->once()->andReturn(true);
            $mock->shouldReceive('hasActiveJob')->once()->andReturn(false);
            $mock->shouldReceive('startPrint')->once()->withArgs(
                fn (string $path, string $name, int $id, ?int $estimate, ?string $camera): bool => $path === Storage::disk('gcode')->path('part.gcode') && $name === 'part.gcode' && $estimate === 5025,
            );
        });

        $this->post(route('printhost.upload'), ['file' => UploadedFile::fake()->createWithContent('part.gcode', self::SAMPLE), 'print' => 'true'], ['X-Api-Key' => self::KEY])
            ->assertCreated();
    }

    public function test_upload_with_print_keeps_the_file_when_the_printer_cannot_print(): void
    {
        $this->mock(PrinterBridge::class, function (MockInterface $mock): void {
            $mock->shouldReceive('activeJob')->andReturnNull();
            $mock->shouldReceive('isConnected')->andReturn(false, true);
            $mock->shouldReceive('hasActiveJob')->andReturn(true);
            $mock->shouldNotReceive('startPrint');
        });

        $this->post(route('printhost.upload'), ['file' => UploadedFile::fake()->createWithContent('part.gcode', 'G28'), 'print' => 'true'], ['X-Api-Key' => self::KEY])
            ->assertStatus(409)
            ->assertHeader('Content-Type', 'text/plain; charset=UTF-8')
            ->assertSee('Stored part.gcode, but the printer is not connected.');
        $this->post(route('printhost.upload'), ['file' => UploadedFile::fake()->createWithContent('part.gcode', 'G28'), 'print' => 'true'], ['X-Api-Key' => self::KEY])
            ->assertStatus(409)
            ->assertSee('Stored part.gcode, but a print is already running.');

        Storage::disk('gcode')->assertExists('part.gcode');
    }

    public function test_upload_refuses_to_replace_the_file_being_printed(): void
    {
        Storage::disk('gcode')->put('part.gcode', 'G28');
        $this->mock(PrinterBridge::class, function (MockInterface $mock): void {
            $mock->shouldReceive('activeJob')->andReturn(['state' => 'printing', 'path' => Storage::disk('gcode')->path('part.gcode')]);
        });

        $this->post(route('printhost.upload'), ['file' => UploadedFile::fake()->createWithContent('part.gcode', self::SAMPLE)], ['X-Api-Key' => self::KEY])
            ->assertStatus(409)
            ->assertSee('part.gcode is being printed right now.');
        $this->assertSame('G28', Storage::disk('gcode')->get('part.gcode'));
    }

    public function test_binary_gcode_is_rejected_with_a_readable_message(): void
    {
        $this->post(route('printhost.upload'), ['file' => UploadedFile::fake()->create('part.bgcode', 1)], ['X-Api-Key' => self::KEY])
            ->assertUnprocessable()
            ->assertHeader('Content-Type', 'text/plain; charset=UTF-8')
            ->assertSee('gcode');
        $this->assertDatabaseCount('gcode_files', 0);
    }
}
