<?php

namespace Tests\Unit;

use App\Services\GcodeMetadata;
use PHPUnit\Framework\TestCase;

class GcodeMetadataTest extends TestCase
{
    public function test_parses_prusaslicer_summary(): void
    {
        $text = <<<'GCODE'
        ; generated by PrusaSlicer 2.8.1+MacOS on 2026-09-01 at 10:00:00 UTC
        M104 S215
        ; estimated first layer printing time (normal mode) = 2m 10s
        ; estimated printing time (normal mode) = 1d 2h 3m 4s
        ; filament used [mm] = 1234.56
        ; filament used [g] = 3.68
        ; total filament used [g] = 3.68
        ; filament_type = PLA
        ; layer_height = 0.2
        ; temperature = 215
        ; bed_temperature = 60
        GCODE;

        $this->assertSame([
            'slicer' => 'PrusaSlicer 2.8.1+MacOS',
            'estimated_seconds' => 93784,
            'filament_mm' => 1234.56,
            'filament_g' => 3.68,
            'filament_type' => 'PLA',
            'layer_height' => 0.2,
            'nozzle_temperature' => 215,
            'bed_temperature' => 60,
        ], (new GcodeMetadata)->parse($text));
    }

    public function test_parses_cura_header(): void
    {
        $text = <<<'GCODE'
        ;FLAVOR:Marlin
        ;TIME:5025
        ;Filament used: 1.23456m
        ;Layer height: 0.28
        ;Generated with Cura_SteamEngine 5.8.0
        M140 S60
        M190 S60
        M104 S200
        GCODE;

        $this->assertSame([
            'slicer' => 'Cura_SteamEngine 5.8.0',
            'estimated_seconds' => 5025,
            'filament_mm' => 1234.6,
            'filament_g' => null,
            'filament_type' => null,
            'layer_height' => 0.28,
            'nozzle_temperature' => 200,
            'bed_temperature' => 60,
        ], (new GcodeMetadata)->parse($text));
    }

    public function test_sums_the_filament_of_every_extruder_and_takes_the_first_material(): void
    {
        $text = "; filament used [mm] = 1000.5, 200.25\r\n; filament used [g] = 3.00, 0.60\r\n; total filament used [g] = 3.60\r\n; filament_type = PETG;PLA\r\n";

        $result = (new GcodeMetadata)->parse($text);

        $this->assertSame(1200.75, $result['filament_mm']);
        $this->assertSame(3.6, $result['filament_g']);
        $this->assertSame('PETG', $result['filament_type']);

        $cura = (new GcodeMetadata)->parse(";Filament used: 1.5m, 0.25m\n");
        $this->assertSame(1750.0, $cura['filament_mm']);
    }

    public function test_unknown_content_yields_nulls(): void
    {
        $result = (new GcodeMetadata)->parse("G28\nG1 X10\n");

        $this->assertSame(array_fill_keys(array_keys($result), null), $result);
    }
}
