<?php

namespace Tests\Unit;

use App\Services\GcodeThumbnail;
use PHPUnit\Framework\TestCase;

class GcodeThumbnailTest extends TestCase
{
    private const string PNG = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==';

    public function test_picks_the_largest_png_block(): void
    {
        $text = "; generated by PrusaSlicer 2.8.1\n"
            .$this->block('thumbnail', '16x16', self::PNG)
            .$this->block('thumbnail', '313x173', self::PNG)
            ."M104 S215\n";

        $image = (new GcodeThumbnail)->parse($text);

        $this->assertNotNull($image);
        $this->assertSame(313, $image['width']);
        $this->assertSame(173, $image['height']);
        $this->assertSame('png', $image['extension']);
        $this->assertSame(base64_decode(self::PNG, true), $image['data']);
    }

    public function test_keeps_jpeg_and_skips_qoi(): void
    {
        $jpeg = base64_encode("\xFF\xD8\xFF\xE0jpeg body");
        $qoi = base64_encode('qoifqoi body');
        $text = "; THUMBNAIL_BLOCK_START\n"
            .$this->block('thumbnail_QOI', '640x480', $qoi)
            .$this->block('thumbnail_JPG', '160x160', $jpeg)
            ."; THUMBNAIL_BLOCK_END\n";

        $image = (new GcodeThumbnail)->parse($text);

        $this->assertNotNull($image);
        $this->assertSame('jpg', $image['extension']);
        $this->assertSame(160, $image['width']);
        $this->assertSame(base64_decode($jpeg, true), $image['data']);
    }

    public function test_returns_null_without_a_usable_block(): void
    {
        $parser = new GcodeThumbnail;

        $this->assertNull($parser->parse("G28\nG1 X10\n"));
        $this->assertNull($parser->parse($this->block('thumbnail', '16x16', 'not base64 !!')));
        $this->assertNull($parser->parse("; thumbnail begin 16x16 10\n; ".self::PNG."\n"));
    }

    private function block(string $label, string $size, string $base64): string
    {
        $lines = array_map(static fn (string $chunk): string => "; {$chunk}", str_split($base64, 32));

        return "; {$label} begin {$size} ".strlen($base64)."\n".implode("\n", $lines)."\n; {$label} end\n";
    }
}
